name: Daily Automatic Backup

# 毎日0:00 JST (15:00 UTC前日) に自動実行
on:
  schedule:
    - cron: '0 15 * * *'  # 15:00 UTC = 翌日0:00 JST
  workflow_dispatch:  # 手動実行も可能

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install @supabase/supabase-js

      - name: Run backup script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          node .github/scripts/backup.js

      - name: Backup completed
        run: |
          echo "✅ Backup completed successfully at $(TZ=Asia/Tokyo date)"
